# Generated by Django 3.2.16 on 2022-12-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(help_text='Максимальная длина 200 символов', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='custom_username',
            field=models.SlugField(help_text='Максимальная длина 200 символов', max_length=200, null=True, unique=True, verbose_name='ник'),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.IntegerField(choices=[(1, 'женщина'), (2, 'мужчина')], default=1, help_text='Ваш пол', verbose_name='пол'),
        ),
    ]
