# Generated by Django 3.2.16 on 2022-12-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221217_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='image',
            new_name='profile_picture',
        ),
    ]
