# Generated by Django 3.2.16 on 2022-12-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_image_account_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='time_zone',
            field=models.CharField(max_length=5, null=True, verbose_name='часовой пояс'),
        ),
    ]
