# Generated by Django 3.2.16 on 2022-12-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account_time_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='time_zone',
            new_name='timezone',
        ),
    ]
