# Generated by Django 3.2.16 on 2022-12-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_time_zone_account_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, help_text='Максимальная длина 200 символов', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='custom_username',
            field=models.SlugField(blank=True, help_text='Максимальная длина 50 символов', null=True, unique=True, verbose_name='ник'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия'),
        ),
    ]
