# Generated by Django 3.2.16 on 2022-12-19 22:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fortune', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата платежа')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('fortune', models.OneToOneField(help_text='Выберите гадание', on_delete=django.db.models.deletion.CASCADE, to='fortune.fortune', verbose_name='гадание')),
            ],
            options={
                'verbose_name': 'покупка гадания',
                'verbose_name_plural': 'покупки гадания',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='баланс')),
                ('bonus', models.DateTimeField(auto_now_add=True, verbose_name='последнее время получения бонуса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'пользовательский счет',
                'verbose_name_plural': 'пользовательские счета',
            },
        ),
    ]
