# Generated by Django 3.2.16 on 2022-12-21 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='баланс')),
                ('bonus', models.DateTimeField(blank=True, null=True, verbose_name='последнее время получения бонуса')),
            ],
            options={
                'verbose_name': 'пользовательский счет',
                'verbose_name_plural': 'пользовательские счета',
            },
        ),
    ]
