# Generated by Django 3.2.16 on 2022-12-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bonus',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последнее время получения бонуса'),
        ),
    ]
