# Generated by Django 3.2.16 on 2022-12-11 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название', max_length=150, verbose_name='название для карт')),
            ],
        ),
        migrations.CreateModel(
            name='Fortune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название', max_length=150, verbose_name='название гадания короткое')),
                ('slug', models.SlugField(default='id-fortune', help_text='Максимальная длина 200 символов', max_length=200, unique=True, verbose_name='идентификатор')),
                ('title_for_main_page', models.CharField(default='Название', max_length=150, verbose_name='название для главной страницы')),
                ('title_for_fortune', models.CharField(default='Название', max_length=150, verbose_name='название гадания')),
                ('type_fortune_telling', models.PositiveIntegerField(default=1, help_text='Тип гадания', validators=[django.core.validators.MinValueValidator(1)], verbose_name='тип гадания')),
                ('card_description', models.TextField(default='Описание', help_text='Описание карты', verbose_name='описание карты')),
                ('default_card_description', models.TextField(default='Описание', help_text='Дефолтное описание товара', verbose_name='дефолтное описание карты')),
                ('number_of_cards', models.PositiveIntegerField(default=1, help_text='Количество карт в гадании', validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество карт')),
                ('price', models.PositiveIntegerField(default=50, help_text='Цена гадания', validators=[django.core.validators.MinValueValidator(1)], verbose_name='цена')),
                ('title_for_cards', models.ManyToManyField(to='fortune.CardTitle', verbose_name='тайтлы для карт')),
            ],
            options={
                'verbose_name': 'гадание',
                'verbose_name_plural': 'Гадания',
            },
        ),
    ]
