# Generated by Django 3.2.16 on 2022-12-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fortune',
            old_name='type_fortune_telling',
            new_name='alignment',
        ),
        migrations.RenameField(
            model_name='fortune',
            old_name='fortune_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='fortune',
            old_name='title_for_main_page',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='fortune',
            old_name='default_card_description',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='fortune',
            name='title_for_fortune',
        ),
        migrations.AddField(
            model_name='fortune',
            name='title_for_AI',
            field=models.CharField(blank=True, help_text='Название гадания, которое будет использоваться в ИИ', max_length=150, verbose_name='название гадания для ИИ'),
        ),
    ]
