# Generated by Django 3.2.16 on 2022-12-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardtitle',
            options={'verbose_name': 'тайтл карты', 'verbose_name_plural': 'Тайтлы для карты'},
        ),
    ]
