# Generated by Django 3.2.16 on 2022-12-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortune',
            name='number_of_cards',
        ),
        migrations.RemoveField(
            model_name='fortune',
            name='title_for_cards',
        ),
        migrations.DeleteModel(
            name='CardTitle',
        ),
    ]
