# Generated by Django 3.2.16 on 2022-12-12 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0002_alter_cardtitle_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortune',
            name='card_description',
        ),
        migrations.RemoveField(
            model_name='fortune',
            name='number_of_cards',
        ),
        migrations.AddField(
            model_name='fortune',
            name='fortune_description',
            field=models.TextField(default='Описание', help_text='Описание карточки с гаданием в главном меню', verbose_name='описание карточки с гаданием'),
        ),
        migrations.AlterField(
            model_name='fortune',
            name='default_card_description',
            field=models.TextField(choices=[(1, 'Обычное'), (2, 'Любовное'), (3, 'Денежное'), (4, 'Работа'), (5, 'День')], default=1, help_text='Тип гадания (какое описание карты будет по умолчанию)', verbose_name='тип гадания'),
        ),
        migrations.AlterField(
            model_name='fortune',
            name='name',
            field=models.CharField(default='Название для админки и т.д.', max_length=150, verbose_name='название гадания'),
        ),
        migrations.AlterField(
            model_name='fortune',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Цена гадания', validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='fortune',
            name='slug',
            field=models.SlugField(help_text='Максимальная длина 200 символов', max_length=200, null=True, unique=True, verbose_name='идентификатор'),
        ),
        migrations.AlterField(
            model_name='fortune',
            name='title_for_cards',
            field=models.ManyToManyField(help_text='Тайтлы для карт (типа ПРОШЛОЕ, НАСТОЯЩЕЕ, БУДУЩЕЕ)', to='fortune.CardTitle', verbose_name='тайтлы для карт'),
        ),
        migrations.AlterField(
            model_name='fortune',
            name='title_for_fortune',
            field=models.CharField(blank=True, help_text='Название гадания, которое будет отображаться на странице гадания', max_length=150, verbose_name='название гадания'),
        ),
        migrations.AlterField(
            model_name='fortune',
            name='title_for_main_page',
            field=models.CharField(help_text='Название гадания, которое будет отображаться на главной странице', max_length=150, null=True, verbose_name='название для главной страницы'),
        ),
        migrations.AlterField(
            model_name='fortune',
            name='type_fortune_telling',
            field=models.IntegerField(choices=[(1, 'Таро 1'), (2, 'Таро 2'), (3, 'Таро 3'), (4, 'Таро 4'), (5, 'Таро 2-3'), (6, 'Таро 2-4'), (7, 'Таро 3-4'), (8, 'Таро звезда'), (9, 'Таро 9')], default=1, help_text='Тип гадания', verbose_name='тип гадания'),
        ),
    ]
