# Generated by Django 3.2.16 on 2022-12-12 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0003_auto_20221212_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortune',
            name='number_of_cards',
            field=models.IntegerField(default=1, help_text='Количество карт в гадании (пожалуйста, убедитесь, что количество карт соответствует типу гадания)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество карт'),
        ),
    ]
