
# Generated by Django 3.2.16 on 2022-12-15 18:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0004_fortune_number_of_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortune',
            name='default_card_description',
            field=models.IntegerField(choices=[(1, 'Обычное'), (2, 'Любовное'), (3, 'Денежное'), (4, 'Работа'), (5, 'День')], default=1, help_text='Тип гадания (какое описание карты будет по умолчанию)', verbose_name='тип гадания'),
        ),
    ]
